### PR TITLE
Fix memory allocation for base-patch16

### LINKED ISSUE #17: Bug: openai clip-vit-base-patch16 failes with memory error
use any of the models here: https://huggingface.co/Green-Sky/ggml_openai_clip-vit-base-patch16

```
clip_model_load: ggml ctx size = 287.12 MB
.................................................clip_model_load: model size =   285.77 MB / num tensors = 397
clip_model_load: 8 MB of compute buffer allocated
clip_model_load: model loadded

ggml_new_tensor_impl: not enough space in the scratch memory pool (needed 16992432, available 16777216)
zsl: /home/green/workspace/clip.cpp/ggml/src/ggml.c:4341: ggml_new_tensor_impl: Assertion `false' failed.
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by monatis**
Closes #17

### CODE REVIEW

**Comment by Green-Sky** [comment]
confirm working
```
clip_model_load: loading model from '../models/openai_clip-vit-base-patch16/openai_clip-vit-base-patch16.ggmlv0.f16.bin' - please wait...
clip_model_load: text model hparams
n_vocab            49408
num_positions      77
t_hidden_size      512
t_n_intermediate   2048
t_projection_dim   512
t_n_head           8
t_n_layer          12

clip_model_load: vision model hparams
image_size         224
patch_size         16
v_hidden_size      768
v_n_intermediate   3072
v_projection_dim   512
v_n_head           12
v_n_layer          12

use_gelu           0
ftype              1

clip_model_load: ggml ctx size = 287.12 MB
.................................................clip_model_load: model size =   285.77 MB / num tensors = 397
clip_model_load: 16 MB of compute buffer allocated
clip_model_load: model loadded

apple = 0.1522
red = 0.1502
human = 0.1427
dog = 0.1404
photo = 0.1388
blue = 0.1381
drawing = 0.1376
```

File: clip.cpp [hunk 1]
```diff
@@ -15,13 +15,20 @@
...
 // after that, remove this and use the mechanism implemented in GGML directly
-size_t get_mem_req_by_size(size_t n_tensors)
+size_t get_mem_req_by_size(const size_t n_tensors, const int n_image_positions)
 {
     size_t mb = 1024 * 1024;
     switch (n_tensors)
     {
     case 397: // base
-        return 8 * mb;
+        if (n_image_positions == 50)
```
Comment (Green-Sky) [inline clip.cpp:24]: why use `==` here and `<=` down below.
also why different param name?

Comment (monatis) [reply clip.cpp:24]: We call this function only once in `clip_model_load` and allocate that memory based the number of positions in the vision model. The scratch buffer, however, is allocated separately in `clip_image_encode` and `clip_text_encode`. `n_image_positions` is fixed for a gien model, but `n_positions` might be different in the case of the text model. So if I used `==` there, the condition would not return `true` for shorter texts.
